const NEURO_TOPICS=[
{topic:"Biogenic Amine Neurotransmitters",questions:[
{year:"Dec 2023",text:"Describe the dopaminergic pathways with a note on its clinical relevance in psychiatry",type:"Essay"},
{year:"Nov 2020",text:"Describe the dopaminergic system in human brain and briefly discuss how it is altered in schizophrenia",type:"Essay"},
{year:"Jun 2020",text:"Describe the dopaminergic system in human central nervous system and its relevance to schizophrenia",type:"Essay"},
{year:"Jun 2018 (S2)",text:"Write an essay on dopaminergic system in the central nervous system and its role in schizophrenia",type:"Essay"},
{year:"Nov 2018 (S1)",text:"Dopaminergic system and its involvement in schizophrenia",type:"Essay"},
{year:"Jun 2022 (S2)",text:"Serotonin-dopamine interactions and their relevance for pathophysiology and treatment of neuropsychiatric disorders",type:"Essay"},
{year:"Dec 2022 (S2)",text:"Serotonin-dopamine interactions and their relevance for pathophysiology and treatment of neuropsychiatric disorders",type:"Essay"},
{year:"Jun 2020 (S1)",text:"Describe the serotonergic system in human central nervous system and its relevance to depression, OCD, and schizophrenia",type:"Essay"},
{year:"Jun 2018 (S1)",text:"Write an essay on serotonergic system in the central nervous system and its role in different psychiatric conditions",type:"Essay"},
{year:"Sep 2025 (P1-Q1)",text:"Write a note on acetylcholine synthesis, metabolism, receptors, and its role in Schizophrenia",type:"Essay"},
{year:"Jun 2020 (S1)",text:"Synthesis, release, and synaptic clearance of dopamine in human brain",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Synthesis and metabolism of dopamine in the central nervous system",type:"Short Note"},
{year:"Nov 2020 (S2)",text:"Synthesis and metabolism of dopamine in the central nervous system",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"Dopamine receptors in the human brain",type:"Short Note"},
{year:"Jun 2021 (S2)",text:"Role of D1 and D2 family of receptors in addiction",type:"Short Note"},
{year:"Jun 2022 (S1)",text:"Role of dopamine in working memory",type:"Short Note"},
{year:"Nov 2020 (S2)",text:"Synthesis and metabolism of serotonin in the central nervous system",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Serotonergic system in psychiatric disorders",type:"Short Note"},
{year:"Nov 2019 (S1)",text:"Serotonin system dysfunction in OCD",type:"Short Note"},
{year:"Jun 2021 (S2)",text:"Serotonin transporter (5-HTT) gene polymorphism and psychiatric disorders",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"How does 5-HT2 receptor modulation influence the efficacy and adverse effects of antipsychotic agents?",type:"Short Note"},
{year:"Dec 2023",text:"Neurotransmitters Serotonin and Norepinephrine",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"Mono-amine hypothesis of depression",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Neurotransmitters in OCD",type:"Short Note"},
{year:"Mar 2025",text:"Write a short note on the dopaminergic pathways in the human brain",type:"Essay"},
{year:"Jun 2024",text:"Role of dopamine in working memory",type:"Short Note"},
]},
{topic:"Amino Acid Neurotransmitters",questions:[
{year:"Jul 2023 (S2)",text:"GABA & Glutamate: Newer Insights on neurotransmission",type:"Essay"},
{year:"Nov 2021 (S2)",text:"Glutamate and its relevance for neuropsychiatric disorders",type:"Essay"},
{year:"Dec 2023 (S2)",text:"Role of NMDA receptors in learning and Long-term potentiation",type:"Essay"},
{year:"Jun 2019 (S2)",text:"Role of GABA in different psychiatric conditions",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Glutamatergic system involvement in OCD",type:"Short Note"},
{year:"Nov 2020 (S2)",text:"NMDA receptor and its role in memory",type:"Short Note"},
{year:"Jul 2023 (S2)",text:"Role of NMDA receptors in learning",type:"Short Note"},
{year:"Mar 2025",text:"Write a short note on the types of glutamate receptors",type:"Essay"},
{year:"Mar 2025",text:"Write a short note on the excitation-inhibition balance in the brain and its relevance for schizophrenia",type:"Essay"},
]},
{topic:"Neuropeptides: Biology, Regulation, and Role in Neuropsychiatric Disorders",questions:[
{year:"Sep 2025 (P1-Q9)",text:"What are neuropeptides? Describe any one neuropeptide in the context of the brain-gut axis",type:"Essay"},
{year:"Sep 2025 (P1-Q2)",text:"What are neuroactive steroids? Discuss the role of pregnanolone and allopregnanolone in the brain and their contemporary clinical relevance",type:"Essay"},
]},
{topic:"Novel Neurotransmitters",questions:[
{year:"Jun 2022 (S1)",text:"Endocannabinoid receptors in the human brain",type:"Short Note"},
{year:"Jun 2022 (S2)",text:"Mirror Neurons and their role in social cognition",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Mirror Neurons and their role in social cognition",type:"Short Note"},
{year:"Dec 2023",text:"Mirror neurons",type:"Short Note"},
{year:"Jun 2024",text:"Endocannabinoid receptors in psychiatric disorders",type:"Short Note"},
{year:"Mar 2025",text:"Write a short note on mirror neurons and their relevance to psychiatry",type:"Essay"},
]},
{topic:"Intraneuronal Signaling",questions:[
{year:"Sep 2025 (P1-Q7)",text:"What are the neuronal signaling pathways? Discuss these pathways with reference to serotonin",type:"Essay"},
{year:"Nov 2019 (S1)",text:"Major neuronal signalling pathways",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Major neuronal signalling pathways",type:"Short Note"},
]},
{topic:"Cellular and Synaptic Basis of Neural Signaling",questions:[
{year:"Jul 2023 (S1)",text:"Principles of Synaptic neurotransmission and synaptic plasticity",type:"Essay"},
{year:"Jun 2020 (S1)",text:"Synaptic plasticity",type:"Short Note"},
{year:"Jun 2020 (S2)",text:"Synaptic plasticity",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"Short term synaptic plasticity",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Synaptic plasticity and psychiatric disorders",type:"Short Note"},
{year:"Jun 2022 (S2)",text:"Synaptic potentiation and memory",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Synaptic potentiation and memory",type:"Short Note"},
{year:"Sep 2024",text:"Describe the resting membrane potential and its significance in neuronal function",type:"Short Note"},
]},
{topic:"Functional Neuroanatomy",questions:[
{year:"Sep 2025 (P1-Q3)",text:"Describe the neuroanatomy of the central executive network and write a note on its functions",type:"Essay"},
{year:"Sep 2025 (P1-Q5)",text:"Describe the functional neuroanatomy of the basal ganglia and explain its role in obsessive-compulsive disorders",type:"Essay"},
{year:"Sep 2025 (P1-Q6)",text:"Describe the major areas of the brain involved in processing and regulating emotions. Add a note on the role of oxytocin",type:"Essay"},
{year:"Jun 2022 (S1)",text:"Functional neuroanatomy of the subcortical structures and its relevance in Psychiatry",type:"Essay"},
{year:"Jun 2021 (S2)",text:"Describe the various cortico-striato-thalamo-cortical circuits and their functional significance",type:"Essay"},
{year:"Nov 2021 (S2)",text:"Functional circuitry of the thalamus",type:"Essay"},
{year:"Nov 2019 (S2)",text:"Describe briefly the anatomy of basal ganglia and discuss their involvement in the pathophysiology of psychiatric disorders",type:"Essay"},
{year:"Nov 2019 (S1)",text:"Describe limbic system and its role in psychiatric disorders",type:"Essay"},
{year:"Nov 2018 (S2)",text:"Describe limbic system and its role in psychiatric disorders",type:"Essay"},
{year:"Dec 2023 (S2)",text:"Describe the functional lobes of the brain along with tests to assess each lobe function",type:"Essay"},
{year:"Jun 2018 (S2)",text:"Write an essay on social brain in humans and its clinical importance",type:"Essay"},
{year:"Jul 2023 (S1)",text:"Describe Fronto-Striatal circuits and its relevance in Psychiatry",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Relevance of fronto-striatal circuit in obsessive-compulsive disorder",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"Salience network and psychiatric disorders",type:"Short Note"},
{year:"Dec 2022 (S1)",text:"Salience network and psychiatric disorders",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"Functional neuroanatomy of cerebellum",type:"Short Note"},
{year:"Jul 2023 (S2)",text:"Role of cerebellum in cognitive and emotional functions",type:"Short Note"},
{year:"Nov 2020 (S2)",text:"Role of cerebellum in cognitive and emotional functions",type:"Short Note"},
{year:"Jun 2021 (S2)",text:"Cerebellar cognitive affective syndrome",type:"Short Note"},
{year:"Nov 2021 (S1)",text:"Neural pathways underlying anxiety",type:"Short Note"},
{year:"Nov 2021 (S1)",text:"Cognitive dysmetria and schizophrenia",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"Cognitive dysmetria",type:"Short Note"},
{year:"Dec 2022 (S1)",text:"Cognitive dysmetria",type:"Short Note"},
{year:"Jun 2020 (S2)",text:"Cerebellum and psychiatric conditions",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Role of cerebellum in psychiatric disorders",type:"Short Note"},
{year:"Nov 2020 (S2)",text:"Papez Circuit",type:"Short Note"},
{year:"Dec 2023 (S2)",text:"Amygdala and its functions",type:"Short Note"},
{year:"Jun 2020 (S2)",text:"Role of amygdala and orbital-medial prefrontal cortex in the physiology of human emotions",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Parts of human limbic system and their relationship with emotion regulation",type:"Short Note"},
{year:"Jul 2023 (S1)",text:"Enumerate Frontal lobe functions and its assessment",type:"Short Note"},
{year:"Jul 2023 (S1)",text:"Describe the CSF pathway with relevant diagram",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Functional brain circuits",type:"Short Note"},
{year:"Dec 2023",text:"Pineal gland",type:"Short Note"},
{year:"Jun 2024",text:"Neuroanatomy of subcortical structures and their relevance in psychiatry",type:"Essay"},
{year:"Sep 2024",text:"Discuss the anatomical structure and function of the basal ganglia in motor control",type:"Short Note"},
{year:"Mar 2025",text:"Write a short note on the anterior cingulate cortex functions and their relationship to obsessive-compulsive disorder",type:"Essay"},
{year:"Mar 2025",text:"Write a short note on thalamic nuclei in the human brain",type:"Essay"},
]},
{topic:"Basic Systems Neuroscience",questions:[
{year:"Jul 2023 (S1)",text:"Neurobiology of emotions",type:"Essay"},
{year:"Jun 2018 (S2)",text:"Neurobiology of emotions",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Write an essay on neurobiology of emotions with specific reference to depression and anxiety disorders",type:"Essay"},
{year:"Jun 2022 (S1)",text:"Neural substrates of memory",type:"Essay"},
{year:"Jun 2021 (S2)",text:"Cellular mechanisms of memory",type:"Essay"},
{year:"Nov 2021 (S1)",text:"Cellular mechanisms of memory",type:"Essay"},
{year:"Jun 2018 (S1)",text:"Write an essay on neural basis of memory with clinical implications",type:"Essay"},
{year:"Nov 2020 (S1)",text:"Describe the neural mechanisms of memory and briefly explain how these are involved in clinical conditions affecting memory",type:"Essay"},
{year:"Dec 2023",text:"Neurobiology of emotions",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Biology of memory",type:"Short Note"},
{year:"Jun 2020 (S1)",text:"Classification of long-term memory in humans",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"Effect of stress on memory",type:"Short Note"},
{year:"Dec 2022 (S1)",text:"Effect of stress on memory",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Neural basis of fear",type:"Short Note"},
{year:"Nov 2019 (S1)",text:"Neural basis of fear and anxiety",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Neural basis of fear and anxiety",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"Fear conditioning in the amygdala through the process of associative learning",type:"Short Note"},
{year:"Dec 2022 (S1)",text:"Fear conditioning in the amygdala through the process of associative learning",type:"Short Note"},
{year:"Jun 2022 (S2)",text:"Neuroglia and their role in pathophysiology of psychiatric disorders",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Neuroglia and their role in pathophysiology of psychiatric disorders",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"Neurobiology of aberrant salience and its relevance in understanding delusions",type:"Short Note"},
{year:"Nov 2021 (S1)",text:"Neurobiology of aberrant salience and its relevance in understanding delusions",type:"Short Note"},
{year:"Jun 2024",text:"Neural substrates in memory",type:"Essay"},
{year:"Sep 2024",text:"Define Neuroplasticity and discuss its role in the pathogenesis of Depression",type:"Short Note"},
{year:"Mar 2025",text:"Discuss the neuroimmunological theory of Depression",type:"Essay"},
]},
{topic:"Neuroscience of Substance Use Disorders",questions:[
{year:"Jun 2021 (S1)",text:"Describe the reward pathway. Explain how different drugs of abuse influence the functioning of the reward pathway",type:"Essay"},
{year:"Dec 2022 (S1)",text:"Describe the reward pathway. Explain how different drugs of abuse influence the functioning of the reward pathway",type:"Essay"},
{year:"Jun 2020 (S1)",text:"Describe the neurobiology of reward system in humans and its relevance to addictive disorders",type:"Essay"},
{year:"Jun 2020 (S2)",text:"Describe the neurobiology of reward system in humans and its relevance to addictive disorders",type:"Essay"},
{year:"Nov 2021 (S1)",text:"Briefly describe the neural circuitry of addiction stages and the neurotransmitters involved",type:"Essay"},
{year:"Nov 2021 (S2)",text:"Neurotransmitters involved in addiction stages",type:"Short Note"},
{year:"Jul 2023 (S2)",text:"Reward circuit and its role in addiction",type:"Short Note"},
{year:"Dec 2023 (S2)",text:"Reward circuit and its role in addiction",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Neural basis of reward system and its relevance to addiction",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Neural basis of addiction",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Neurobiology of abnormal compulsive behavior in humans",type:"Short Note"},
{year:"Jun 2020 (S2)",text:"Neurobiology of compulsive behavior in humans",type:"Short Note"},
{year:"Jun 2018 (S2)",text:"Neurobiology of addiction",type:"Short Note"},
{year:"Jul 2023 (S1)",text:"Write a note on Anti-craving agents",type:"Short Note"},
]},
{topic:"Basic Science of Sleep",questions:[
{year:"Sep 2025 (P1-Q8)",text:"Discuss the role of orexin and melatonin in sleep",type:"Essay"},
{year:"Dec 2023",text:"Neurobiology of sleep and sleep regulation",type:"Essay"},
{year:"Nov 2020 (S1)",text:"Describe the stages of sleep and briefly discuss the role of different neurotransmitters in the physiology of sleep",type:"Essay"},
{year:"Jul 2023 (S1)",text:"Neuro-physiology of Sleep",type:"Short Note"},
{year:"Jul 2023 (S2)",text:"Neurophysiology of Sleep",type:"Short Note"},
{year:"Jun 2022 (S2)",text:"Neurophysiological basis of NREM sleep",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Neurophysiological basis of NREM sleep",type:"Short Note"},
{year:"Nov 2021 (S1)",text:"Normal human sleep stages",type:"Short Note"},
{year:"Jun 2020 (S1)",text:"Role of different neurotransmitters in the physiology of sleep",type:"Short Note"},
{year:"Nov 2020 (S2)",text:"Stages of sleep",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Role of sleep in psychiatric disorders",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"Stages of sleep and their clinical relevance",type:"Short Note"},
{year:"Jun 2018 (S2)",text:"Stages of sleep and their clinical relevance",type:"Short Note"},
{year:"Sep 2024",text:"Examine the roles of key neurotransmitters like GABA, serotonin, norepinephrine, and acetylcholine in promoting sleep and wakefulness. Additionally, discuss the significance of REM sleep in emotional processing and memory consolidation and how disturbances in REM sleep are linked to mood disorders",type:"Essay"},
]},
{topic:"Basic Science of Appetite",questions:[
{year:"Sep 2025 (P1-Q10)",text:"What is the mechanism of central regulation of appetite? Describe the role of leptin and ghrelin",type:"Essay"},
]},
{topic:"Psychoneuroendocrinology",questions:[
{year:"Jun 2019 (S1)",text:"Write an essay on psychoneuroendocrinological basis of psychiatric disorders with specific emphasis on depression",type:"Essay"},
{year:"Dec 2023",text:"Neurobiology of stress",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"Neuroendocrine hypotheses underlying depression",type:"Short Note"},
{year:"Jun 2024",text:"Neuroendocrine hypothesis of depression",type:"Short Note"},
{year:"Jun 2022 (S1)",text:"Neuroendocrine hypothesis of depression",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"Psychiatric manifestations of endocrine disorders",type:"Short Note"},
{year:"Dec 2022 (S1)",text:"Psychiatric manifestations of endocrine disorders",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Interaction between stress and endocrine system in psychiatric conditions",type:"Short Note"},
{year:"Jun 2020 (S1)",text:"Relationship between stress and hypothalamo-pituitary-adrenal axis",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"Hypothalamic-pituitary-adrenal axis and psychiatry",type:"Short Note"},
{year:"Jun 2021 (S2)",text:"Prenatal stress and psychiatric disorders",type:"Short Note"},
{year:"Nov 2021 (S1)",text:"Prenatal stress and psychiatric disorders",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Heart rate variability in psychiatric disorders",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"Heart rate variability in psychiatric disorders",type:"Short Note"},
]},
{topic:"Immune System and Central Nervous System Interactions",questions:[
{year:"Jul 2023 (S2)",text:"Psychoneuroimmunology – relevance to psychiatric disorders",type:"Essay"},
{year:"Jun 2022 (S2)",text:"Neuroimmunology of depression",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Neuroimmunology of depression",type:"Short Note"},
{year:"Jun 2021 (S2)",text:"Anti-neuronal antibodies and acute psychiatric presentations",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"Gut Microbiome and its relevance in Psychiatry",type:"Short Note"},
{year:"Dec 2022 (S1)",text:"Gut Microbiome and its relevance in Psychiatry",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Immunological basis of psychiatric disorders",type:"Short Note"},
{year:"Jun 2018 (S2)",text:"Role of immune system in depression and anxiety disorders",type:"Short Note"},
{year:"Sep 2024",text:"Discuss the gut-brain axis and its implications for psychiatric disorders",type:"Short Note"},
{year:"Sep 2024",text:"Discuss the role of neuroinflammation in the development of psychiatric disorders, with examples",type:"Short Note"},
]},
{topic:"Genome, Transcriptome and Proteome: Molecular Genetics",questions:[
{year:"Sep 2025 (P1-Q4)",text:"What are endophenotypes? Write a short note on endophenotypes in bipolar disorders",type:"Essay"},
{year:"Jun 2019 (S1)",text:"Write an essay on gene X environment interaction in the causation of psychiatric disorders with specific emphasis on schizophrenia",type:"Essay"},
{year:"Jul 2023 (S1)",text:"Gene-environment interactions and epigenetics",type:"Short Note"},
{year:"Dec 2023",text:"Gene-environment interactions and epigenetics",type:"Short Note"},
{year:"Jun 2022 (S2)",text:"Epigenetics of schizophrenia spectrum disorders",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Epigenetics of schizophrenia spectrum disorders",type:"Short Note"},
{year:"Jun 2018 (S2)",text:"Gene X environment interaction in psychiatric disorders",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"Epigenetics in psychiatric disorders",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Role of epigenetics in psychiatry",type:"Short Note"},
{year:"Nov 2020 (S2)",text:"Role of epigenetics in psychiatry",type:"Short Note"},
{year:"Jun 2020 (S1)",text:"Role of epigenetics in psychiatric disorders",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Family studies in bipolar disorder",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Family studies in schizophrenia",type:"Short Note"},
{year:"Jun 2021 (S2)",text:"Serotonin transporter (5-HTT) gene polymorphism and psychiatric disorders",type:"Short Note"},
{year:"Sep 2024",text:"Discuss the role of gene-environment interactions in the etiology of psychiatric disorders and critically examine its role in transgenerational transmission. Additionally, discuss how DNA methylation, histone modification, and non-coding RNAs contribute to the development and progression of MDD",type:"Essay"},
{year:"Mar 2025",text:"Polymerase chain reaction",type:"Essay"},
]},
{topic:"Gene Mapping Investigations of Psychiatric Disorders",questions:[
{year:"Jun 2022 (S1)",text:"Genome-wide association studies in Psychiatry",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Genome-Wide Association Study (GWAS) and psychiatric disorders",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Genome-wide association studies in psychiatry",type:"Short Note"},
{year:"Nov 2019 (S1)",text:"Concept of endophenotypes and its application in psychiatric research",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Concept of endophenotypes and its application in psychiatric research",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Concept of endophenotypes and its application in psychiatric research",type:"Short Note"},
{year:"Jun 2024",text:"GWAS in psychiatry",type:"Short Note"},
{year:"Mar 2025",text:"What is GWAS? Discuss its relevance in psychiatric disorders",type:"Essay"},
]},
{topic:"Applied Electrophysiology",questions:[
{year:"Jul 2023 (S2)",text:"Note on Mood Stabilizers",type:"Short Note"},
{year:"Dec 2023 (S2)",text:"EEG in Psychiatry",type:"Short Note"},
{year:"Nov 2019 (S1)",text:"Applications of fMRI in psychiatry research",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Application of fMRI in psychiatric research",type:"Short Note"},
{year:"Dec 2023 (S2)",text:"Neuromodulation in psychiatry",type:"Short Note"},
{year:"Dec 2023 (S2)",text:"Neurological soft signs in psychiatry",type:"Short Note"},
{year:"Sep 2024",text:"Discuss the relevance of network neuroscience in predicting treatment outcomes in Psychiatry",type:"Short Note"},
{year:"Mar 2025",text:"Evoked Response Potentials and its relevance in psychiatric disorders",type:"Essay"},
]},
{topic:"Animal Models in Psychiatry",questions:[
{year:"Jun 2022 (S1)",text:"Animal models of psychiatric disorders",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Animal models of depression",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Animal models of depression",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Animal models of OCD",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Theory of mind",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Theory of mind",type:"Short Note"},
{year:"Jun 2024",text:"Animal models in psychiatric disorders",type:"Short Note"},
]},
{topic:"Pain Systems: Interface with Affective and Motivational Mechanisms",questions:[
{year:"Jun 2021 (S1)",text:"Describe the neural mechanism of pain perception and regulation in the brain",type:"Essay"},
{year:"Dec 2022 (S1)",text:"Describe the neural mechanism of pain perception and its regulation",type:"Essay"},
{year:"Nov 2020 (S2)",text:"Describe the physiology of pain and how peripheral and central systems influence it",type:"Essay"},
{year:"Jun 2022 (S2)",text:"Biological basis of various pharmacological strategies for control of pain",type:"Essay"},
{year:"Dec 2022 (S2)",text:"Biological basis of various pharmacological strategies for control of pain",type:"Essay"},
{year:"Jul 2023 (S2)",text:"Neural basis of pain",type:"Short Note"},
{year:"Dec 2023 (S2)",text:"Neural basis of Pain",type:"Short Note"},
{year:"Jun 2022 (S1)",text:"Gate control theory of pain",type:"Short Note"},
{year:"Jun 2020 (S2)",text:"Neural basis of pain",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Central modulation of pain",type:"Short Note"},
{year:"Nov 2021 (S1)",text:"Neural basis of comorbidity of chronic pain and depression",type:"Short Note"},
{year:"Jun 2024",text:"Gate control theory of pain",type:"Short Note"},
]},
{topic:"Miscellaneous – Neurosciences",questions:[
{year:"Jun 2019 (S2)",text:"Write an essay on pathophysiology and pathology of dementias",type:"Essay"},
{year:"Jun 2020 (S2)",text:"Neuropathology of Alzheimer's disease",type:"Short Note"},
{year:"Nov 2019 (S1)",text:"Neuropathology in Alzheimer's dementia",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Neuropathology of Alzheimer's disease",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Neuropathology of schizophrenia",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Amyloid plaques",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"Amyloid plaques",type:"Short Note"},
{year:"Jun 2018 (S2)",text:"Neurofibrillary tangles",type:"Short Note"},
]},
];
const PSYCH_TOPICS=[
{topic:"Learning",questions:[
{year:"Jun 2021 (S1)",text:"Discuss the key principles of classical conditioning theory and their role in therapeutic procedures",type:"Essay"},
{year:"Nov 2021 (S2)",text:"Explain the theoretical concept of classical conditioning. Briefly describe any two behavioural techniques based on classical conditioning",type:"Essay"},
{year:"Jun 2022 (S1)",text:"Explain the theoretical concept of operant conditioning. Enumerate any two behavioural techniques based on operant conditioning",type:"Essay"},
{year:"Sep 2024",text:"Discuss on the classical and operant conditioning principles in detail. Additionally, discuss the application of learning theories in clinical practice",type:"Essay"},
{year:"Nov 2019 (S1)",text:"Describe theories of learning and their application in psychiatry",type:"Essay"},
{year:"Nov 2020 (S2)",text:"What is behavior therapy? Discuss in detail the techniques commonly used in behavior therapy",type:"Essay"},
{year:"Jul 2023 (S1)",text:"Discuss the application of learning principles in psychological interventions",type:"Short Note"},
{year:"Jun 2024",text:"Theoretical concepts of operant conditioning and two applications in behavioural therapy",type:"Essay"},
{year:"Dec 2022 (S1)",text:"Discuss operant conditioning and any two of its clinical applications",type:"Short Note"},
{year:"Jun 2020 (S1)",text:"Operant conditioning procedures",type:"Short Note"},
{year:"Jun 2018 (S2)",text:"Operant conditioning",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Theories of learning and their application to behavior therapy",type:"Short Note"},
{year:"Jun 2018 (S2)",text:"Latent learning",type:"Short Note"},
{year:"Dec 2023 (S1)",text:"Discuss any two behaviour therapy techniques and their learning principles",type:"Short Note"},
{year:"Jun 2022 (S2)",text:"Briefly outline social learning theories and their clinical applications",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Briefly outline social learning theories and their clinical applications",type:"Short Note"},
{year:"Jun 2021 (S2)",text:"Basic principles of social learning theory and its applications in clinical practice",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"Social learning theory - principles and applications in social skills training",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"Principles of exposure and response prevention and common pitfalls in the practice of ERP",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Systematic desensitization",type:"Short Note"},
{year:"Nov 2021 (S1)",text:"Discuss any two behaviour therapy techniques based on operant conditioning",type:"Short Note"},
]},
{topic:"Memory",questions:[
{year:"Sep 2025",text:"Define memory and describe the types of memory",type:"Essay"},
{year:"Nov 2018 (S2)",text:"Discuss processes and forms of memory. What are the dysfunctions of memory?",type:"Essay"},
{year:"Jun 2024",text:"Models of Working memory and its application in daily life",type:"Short Note"},
{year:"Jun 2022 (S1)",text:"Discuss the models of working memory and its role in everyday life",type:"Short Note"},
{year:"Dec 2023 (S2)",text:"Discuss memory dysfunctions and cognitive retraining techniques for the same",type:"Short Note"},
{year:"Nov 2021 (S1)",text:"Briefly enumerate the various types of memory and its dysfunctions",type:"Short Note"},
{year:"Jun 2021 (S2)",text:"What is confabulation? How is confabulation evaluated and addressed in clinical practice?",type:"Short Note"},
{year:"Jun 2020 (S1)",text:"Memory - types of dysfunction and methods of assessment",type:"Short Note"},
{year:"Nov 2019 (S1)",text:"Assessment of memory",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Information processing in memory",type:"Short Note"},
]},
{topic:"Cognition",questions:[
{year:"Sep 2025",text:"Write a note on the instruments for brief screening of cognitive function and common indications for a detailed neuropsychological assessment",type:"Essay"},
{year:"Dec 2023 (S2)",text:"Explain principles and indications of neuropsychological assessments and outline executive function tests",type:"Essay"},
{year:"Dec 2023 (S1)",text:"Discuss cognitive functions and assessments of occipital and parietal lobe",type:"Essay"},
{year:"Mar 2025",text:"Neuropsychological assessment of an older adult with cognitive complaint",type:"Essay"},
{year:"Nov 2021 (S1)",text:"Discuss the principles, rationale and indications of the use of neuropsychological assessments",type:"Essay"},
{year:"Nov 2020 (S2)",text:"What are the components of neuropsychological assessment? Describe in detail the clinical assessment of memory",type:"Essay"},
{year:"Jun 2021 (S1)",text:"What is intelligence? Discuss various theories of intelligence",type:"Essay"},
{year:"Nov 2021 (S2)",text:"Define Intelligence. Discuss in detail any three theories of intelligence",type:"Essay"},
{year:"Sep 2025",text:"Write a brief note on the theories of intelligence",type:"Short Note"},
{year:"Jul 2023 (S1)",text:"Write a note on - Intelligence; concept, theories & assessments",type:"Short Note"},
{year:"Jun 2022 (S2)",text:"Briefly outline the important theories of intelligence",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Briefly outline the important theories of intelligence",type:"Short Note"},
{year:"Mar 2025",text:"Assessment of Intelligence Quotient. Name few intelligence tests",type:"Essay"},
{year:"Jun 2024",text:"Tests of intelligence used in India",type:"Short Note"},
{year:"Jun 2022 (S1)",text:"Briefly outline the tests of intelligence commonly used in India",type:"Short Note"},
{year:"Dec 2023 (S1)",text:"Discuss any two theories of intelligence and their implications in intelligence assessment",type:"Short Note"},
{year:"Jun 2021 (S2)",text:"Discuss nature vs. nurture argument in understanding intelligence",type:"Short Note"},
{year:"Jun 2020 (S1)",text:"Theories of intelligence",type:"Short Note"},
{year:"Jun 2020 (S2)",text:"Theories of intelligence",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Newer tests of intelligence",type:"Short Note"},
{year:"Jun 2021 (S2)",text:"Structure of neuropsychological assessment",type:"Short Note"},
{year:"Jul 2023 (S1)",text:"Discuss about temporal lobe deficits and cognitive assessment in temporal lobe",type:"Short Note"},
{year:"Sep 2024",text:"Describe the neuropsychological assessments of the Pre-Frontal Lobe function",type:"Short Note"},
{year:"Dec 2022 (S1)",text:"Neuropsychological tests used in assessment of frontal lobe functions",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"Outline the neuropsychological tests used in assessment of frontal lobe dysfunction",type:"Short Note"},
{year:"Jun 2022 (S2)",text:"Outline the neuropsychological tests used in assessment of parietal lobe dysfunction",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Outline the neuropsychological tests used in assessment of parietal lobe dysfunctions",type:"Short Note"},
{year:"Nov 2020 (S2)",text:"Assessment of frontal lobe functions",type:"Short Note"},
{year:"Jun 2020 (S2)",text:"Assessment of frontal lobe functions",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Tests of Attention",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Relevance of neuropsychological assessment in clinical practice",type:"Short Note"},
{year:"Jun 2018 (S2)",text:"Wisconsin Card Sorting Test",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"Tower of London Test",type:"Short Note"},
{year:"Nov 2019 (S1)",text:"Neuropsychological impairments in OCD",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Neuropsychological impairments in Schizophrenia",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Neuropsychological impairments in bipolar disorder",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Assessment of abstraction and concept formation",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Describe neuro-cognitive model of schizophrenia. Explain cognitive remediation therapy and its relevance in the management of schizophrenia",type:"Essay"},
]},
{topic:"Motivation & Emotion",questions:[
{year:"Jun 2022 (S1)",text:"Define emotion. Discuss the various theories of emotion",type:"Essay"},
{year:"Nov 2020 (S2)",text:"Theories of emotion",type:"Short Note"},
{year:"Jun 2020 (S1)",text:"Theories of Emotion",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Emotional regulation",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"The role of sympathetic and parasympathetic nervous system in emotion",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"The general adaptation syndrome",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Coping and coping skills training",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Clinical application of positive psychology",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"Social motives and its types",type:"Short Note"},
{year:"Jun 2024",text:"What is emotion? Discuss the theories of emotion",type:"Essay"},
{year:"Sep 2024",text:"Explain the basic concepts of motivation and emotion in psychological theory",type:"Short Note"},
{year:"Mar 2025",text:"Theories of Motivation",type:"Essay"},
{year:"Dec 2023 (S2)",text:"Discuss clinical application of motivation theories",type:"Short Note"},
{year:"Dec 2022 (S1)",text:"Theories of motivation",type:"Short Note"},
{year:"Jun 2022 (S2)",text:"Critically analyse Maslow's theory of motivation and its relevance in contemporary society",type:"Short Note"},
]},
{topic:"Personality",questions:[
{year:"Mar 2025",text:"Methods of assessment of Personality. Provide example for each method",type:"Essay"},
{year:"Sep 2024",text:"Critically evaluate psychodynamic theories and their application in therapy. Additionally, discuss the relevance of psychodynamic concepts in understanding personality disorders",type:"Essay"},
{year:"Jul 2023 (S1)",text:"Write a note on Theories of Personality. Critique on multidimensional approach to personality classification. Briefly write a note on personality assessment",type:"Essay"},
{year:"Dec 2022 (S1)",text:"Enumerate the types of personality assessment. Discuss in detail one test each belonging to different categories",type:"Essay"},
{year:"Jun 2020 (S1)",text:"Critically discuss methods to assess personality",type:"Essay"},
{year:"Sep 2025",text:"Discuss the projective tests for personality assessment",type:"Essay"},
{year:"Jun 2018 (S2)",text:"What is a projective test? Describe Rorschach test",type:"Essay"},
{year:"Jun 2024",text:"Trait theories in personality and its clinical relevance",type:"Short Note"},
{year:"Jun 2022 (S1)",text:"Outline the trait theories of personality and its relevance in present day clinical practice",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"Discuss the indications of using projective and objective personality assessments with suitable examples",type:"Short Note"},
{year:"Dec 2023 (S2)",text:"Discuss indications of projective assessment and self-rated personality assessment in clinical practice",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Assessment of personality",type:"Short Note"},
{year:"Jul 2023 (S1)",text:"Discuss about projective assessment and its use in psychological intervention",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Rationale and indications of projective tests in clinical mental health",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Projective tests",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"Thematic Apperception Test",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Object Sorting Test",type:"Short Note"},
{year:"Nov 2020 (S2)",text:"Structure of personality according to Freud",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Object-relation theory",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"Compare and contrast the psychosexual stages of Freud with the psychosocial stages of Erikson",type:"Short Note"},
{year:"Jun 2020 (S2)",text:"Carl Rogers humanistic theory of personality",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Humanistic theories of personality",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Humanistic theories of personality",type:"Short Note"},
{year:"Jun 2018 (S2)",text:"Humanistic psychology",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Enumerate the various humanistic and existential theories and discuss their clinical applications",type:"Essay"},
{year:"Jun 2019 (S2)",text:"Discuss humanistic and existential theory of human behaviour and describe their application in therapy of psychiatric disorders",type:"Essay"},
]},
{topic:"Psychopathology",questions:[
{year:"Mar 2025",text:"Stress diathesis model of depression",type:"Essay"},
{year:"Sep 2024",text:"How did Brown and Harris study (1978) contribute to developing the vulnerability-stress model in Psychiatry?",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Discuss the various theories proposed to understand the psychological underpinnings of psychotic symptoms",type:"Essay"},
{year:"Dec 2023 (S2)",text:"Explain cognitive and psychological model of affective disorders",type:"Essay"},
{year:"Nov 2021 (S1)",text:"Explain the various psychosocial models of depression",type:"Essay"},
{year:"Jun 2020 (S1)",text:"What are the psychosocial and cognitive models of affective disorders?",type:"Essay"},
{year:"Nov 2020 (S2)",text:"Psychological theories of psychotic symptoms",type:"Short Note"},
{year:"Jun 2020 (S2)",text:"Psychological theories of hallucinations",type:"Short Note"},
{year:"Jun 2020 (S1)",text:"Psychological theories of delusional thinking",type:"Short Note"},
{year:"Jun 2018 (S2)",text:"Cognitive theories of delusion formation",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Psychological theories of mania",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Life events and depression",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Life events and Depression",type:"Short Note"},
{year:"Dec 2022 (S1)",text:"Metacognition and psychotic symptoms",type:"Short Note"},
{year:"Jun 2020 (S2)",text:"Psychological theories of panic",type:"Short Note"},
]},
{topic:"Psychotherapy",subgroups:[
{subgroup:"Cognitive Behaviour Therapy (CBT)",questions:[
{year:"Sep 2025",text:"Discuss the principles and clinical applications of CBT in depression",type:"Essay"},
{year:"Jul 2023 (S1)",text:"Cognitive Behaviour Therapy; Concepts, Principles and Applications",type:"Essay"},
{year:"Dec 2022 (S1)",text:"Discuss Beck's longitudinal formulation and its application in clinical practice",type:"Essay"},
{year:"Nov 2020 (S1)",text:"What are the basic tenets of CBT? Describe and discuss two major applications of CBT in clinical practice in India",type:"Essay"},
{year:"Dec 2023 (S2)",text:"Discuss principles and applications of CBT",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Describe the cognitive-behavioral model of OCD. Explain CBT and its relevance in management of OCD",type:"Essay"},
{year:"Jun 2018 (S1)",text:"Discuss the cognitive-behavioral model of generalized anxiety disorder. Describe the cognitive-behavior therapy for generalized anxiety disorder",type:"Essay"},
{year:"Jun 2018 (S2)",text:"Discuss the cognitive-behavioral model of panic disorder. Describe briefly the cognitive-behavior therapy for panic disorder",type:"Essay"},
{year:"Jun 2021 (S2)",text:"Discuss cognitive theory of anxiety disorders",type:"Essay"},
{year:"Nov 2018 (S1)",text:"Discuss cognitive-behavioral theories of anxiety disorders",type:"Essay"},
{year:"Jun 2024",text:"NATs, DAS, Core beliefs in CBT model with examples",type:"Short Note"},
{year:"Jun 2022 (S1)",text:"Distinguish between core beliefs, negative automatic thoughts and assumptions with suitable examples",type:"Short Note"},
{year:"Jun 2022 (S2)",text:"Briefly describe steps in cognitive restructuring",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Briefly describe steps in cognitive restructuring",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"What are cognitive distortions/errors in thinking? Discuss with examples",type:"Short Note"},
{year:"Jun 2024",text:"Psychosocial models of OCD",type:"Short Note"},
{year:"Jun 2022 (S1)",text:"Outline the various psychosocial theories of OCD",type:"Short Note"},
{year:"Mar 2025",text:"Cognitive models of panic disorder",type:"Essay"},
{year:"Nov 2019 (S2)",text:"Cognitive behavioral model of anxiety disorders",type:"Short Note"},
{year:"Jun 2020 (S2)",text:"Basic principles of CBT in OCD",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Cognitive behavioral understanding of OCD",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Cognitive behavioural therapy for panic disorder",type:"Short Note"},
{year:"Nov 2019 (S1)",text:"Cognitive behavioral model for social anxiety",type:"Short Note"},
{year:"Dec 2023 (S2)",text:"What are the principles of mindfulness-based interventions, and compare their efficacy to other forms of psychotherapy?",type:"Short Note"},
]},
{subgroup:"Dialectical Behaviour Therapy (DBT)",questions:[
{year:"Sep 2025",text:"Write a short note on Dialectical Behaviour Therapy",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Discuss psychological theories of personality disorder and describe dialectical behaviour therapy for borderline personality disorder",type:"Essay"},
{year:"Nov 2020 (S2)",text:"Dialectical behavior therapy and personality disorders",type:"Short Note"},
]},
{subgroup:"Psychodynamic Therapy",questions:[
{year:"Mar 2025",text:"Brief Psychodynamic Psychotherapy",type:"Essay"},
{year:"Jun 2020 (S2)",text:"Discuss the principles of psychodynamic psychotherapy. What is its current status?",type:"Essay"},
{year:"Jul 2023 (S1)",text:"Discuss various techniques used in psychodynamic therapy",type:"Short Note"},
{year:"Dec 2023 (S1)",text:"Discuss various techniques used in psychodynamic therapy",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Transference and countertransference in psychodynamic psychotherapy",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"Discuss the role of transference and countertransference in therapy",type:"Short Note"},
{year:"Dec 2022 (S1)",text:"Types of resistance in psychotherapy",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Discuss defence mechanisms. Illustrate the role of defence mechanisms in psychiatric disorders",type:"Essay"},
{year:"Jun 2021 (S2)",text:"Ego defence mechanisms",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Defence mechanisms",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Defense mechanisms and their role in human behavior",type:"Short Note"},
{year:"Nov 2021 (S1)",text:"Differentiate between any 3 mature and immature defense mechanisms with suitable examples",type:"Short Note"},
]},
{subgroup:"Existential & Humanistic Therapy",questions:[
{year:"Sep 2025",text:"Discuss the application of Existential Theories in Psychotherapy",type:"Essay"},
{year:"Dec 2023 (S2)",text:"Discuss the application of existential and humanistic theories in psychotherapy",type:"Short Note"},
{year:"Nov 2021 (S1)",text:"Application of existential therapy in clinical practice",type:"Short Note"},
]},
{subgroup:"Brief & Other Psychotherapies",questions:[
{year:"Dec 2023 (S1)",text:"Define psychotherapy and discuss three major types of psychotherapy",type:"Essay"},
{year:"Jun 2022 (S2)",text:"Define psychotherapy. Enumerate brief psychotherapies and provide details of two brief psychotherapeutic approaches",type:"Essay"},
{year:"Nov 2021 (S1)",text:"Outline the various types of brief psychotherapy",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Motivational Interviewing",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"Discuss the psychosocial theories of addictive behavior. Describe motivational interviewing for treatment of addiction",type:"Essay"},
{year:"Mar 2025",text:"Psychosocial theories of addictive disorders",type:"Essay"},
{year:"Jun 2020 (S2)",text:"What are the psychosocial theories of Addiction? How are these theories useful in planning psychological interventions?",type:"Essay"},
{year:"Dec 2023 (S1)",text:"Explain psychosocial theories of addiction",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"Psychosocial interventions for addictive disorders",type:"Short Note"},
]},
]},
{topic:"Yoga & Ancient Indian Psychology",questions:[
{year:"Jun 2024",text:"Ancient Indian concepts in positive mental health",type:"Short Note"},
{year:"Mar 2025",text:"Ancient Indian Concepts of Psychotherapy",type:"Essay"},
{year:"Sep 2024",text:"Detail the relevance of ancient Indian concepts in contemporary psychotherapy",type:"Short Note"},
{year:"Dec 2022 (S1)",text:"Therapeutic techniques from Atharva veda",type:"Short Note"},
{year:"Jul 2023 (S1)",text:"Application of Ancient Indian concepts in Psychotherapy",type:"Short Note"},
{year:"Jun 2022 (S1)",text:"Briefly describe ancient Indian concepts of positive mental health",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"Explain the relevance of ancient Indian concepts of emotions in contemporary clinical practice",type:"Short Note"},
{year:"Jun 2021 (S2)",text:"Discuss the major components of mind as conceptualized by various schools of Indian thought",type:"Short Note"},
{year:"Jun 2020 (S1)",text:"Ancient Indian thought and its use in psychotherapy",type:"Short Note"},
{year:"Jun 2022 (S2)",text:"Explain the relevance of ancient Indian concepts of personality in contemporary clinical practice",type:"Short Note"},
{year:"Dec 2022 (S2)",text:"Explain the relevance of ancient Indian concepts of personality in contemporary clinical practice",type:"Short Note"},
{year:"Nov 2021 (S1)",text:"Ancient Indian concept of personality and its present day relevance",type:"Short Note"},
{year:"Nov 2020 (S2)",text:"Yoga and its role in mental health",type:"Short Note"},
{year:"Nov 2020 (S1)",text:"Role of meditation in promoting mental health",type:"Short Note"},
{year:"Jun 2019 (S2)",text:"Application of yoga and mindfulness in mental health",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Role of Yoga and Meditation in mental health care",type:"Short Note"},
]},
{topic:"Social Psychology",questions:[
{year:"Sep 2024",text:"Expand on the intersection of gender and mental health from a sociological perspective",type:"Short Note"},
{year:"Nov 2019 (S1)",text:"Attachment theory",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Attachment theory and its relevance to understanding human behavior",type:"Short Note"},
{year:"Nov 2018 (S1)",text:"Expressed emotions and psychiatric disorders",type:"Short Note"},
{year:"Sep 2025",text:"Write a short note on the social determinants of mental health",type:"Short Note"},
{year:"Sep 2025",text:"Discuss the cultural aspects of mental health",type:"Short Note"},
{year:"Nov 2019 (S1)",text:"Social determinants of depression",type:"Short Note"},
{year:"Nov 2019 (S1)",text:"Culture and course of schizophrenia",type:"Short Note"},
{year:"Nov 2018 (S2)",text:"Culture and course of Schizophrenia",type:"Short Note"},
]},
{topic:"Developmental Psychology",questions:[
{year:"Mar 2025",text:"Piaget's stages of intellectual development",type:"Essay"},
{year:"Sep 2024",text:"Outline the key stages of cognitive development according to Jean Piaget",type:"Short Note"},
{year:"Sep 2025",text:"List Erikson's psychosocial stages of development and discuss them",type:"Essay"},
{year:"Jun 2022 (S2)",text:"Briefly describe Erik Erikson's stages of psychosocial development. How do mastery of these stages or conflicts during these stages potentially manifest in adulthood?",type:"Essay"},
{year:"Jun 2021 (S2)",text:"Explain at least 3 stages of Erikson's theory of psychosocial development. Illustrate what successful and unsuccessful resolution would look like in each of the stages you choose to explain",type:"Essay"},
{year:"Nov 2020 (S1)",text:"Critically discuss and evaluate Piaget's theory of cognitive development",type:"Essay"},
{year:"Dec 2023 (S1)",text:"Explain Erik Erikson's stages of development and their implications for mental health",type:"Short Note"},
{year:"Nov 2021 (S2)",text:"Outline the Piaget's stages of cognitive development",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"Piaget's stages of cognitive development",type:"Short Note"},
{year:"Nov 2019 (S2)",text:"Piagetian model of cognitive development",type:"Short Note"},
{year:"Jun 2019 (S1)",text:"Cognitive development in children",type:"Short Note"},
{year:"Jun 2018 (S2)",text:"Stages of psychosocial developments as described by Erikson",type:"Short Note"},
{year:"Nov 2020 (S2)",text:"Development of language",type:"Short Note"},
{year:"Jun 2021 (S1)",text:"What are the milestones that mark language development from infancy to late childhood?",type:"Short Note"},
{year:"Jun 2018 (S1)",text:"Stages of language development",type:"Short Note"},
{year:"Dec 2023 (S1)",text:"Discuss the components you must cover while psychoeducating the parents of a child with mental retardation",type:"Short Note"},
{year:"Jun 2020 (S1)",text:"Common developmental disorders",type:"Short Note"},
]},
];
const YEAR_DATA={
neuro:[
{year:"Sep 2025",paper:"Paper 1: Basic Neurosciences",questions:[
{text:"Write a note on acetylcholine synthesis, metabolism, receptors, and its role in Schizophrenia",type:"Essay"},
{text:"What are neuroactive steroids? Discuss the role of pregnanolone and allopregnanolone in the brain and their contemporary clinical relevance",type:"Essay"},
{text:"Describe the neuroanatomy of the central executive network and write a note on its functions",type:"Essay"},
{text:"What are endophenotypes? Write a short note on endophenotypes in bipolar disorders",type:"Essay"},
{text:"Describe the functional neuroanatomy of the basal ganglia and explain its role in obsessive-compulsive disorders",type:"Essay"},
{text:"Describe the major areas of the brain involved in processing and regulating emotions. Add a note on the role of oxytocin",type:"Essay"},
{text:"What are the neuronal signaling pathways? Discuss these pathways with reference to serotonin",type:"Essay"},
{text:"Discuss the role of orexin and melatonin in sleep",type:"Essay"},
{text:"What are neuropeptides? Describe any one neuropeptide in the context of the brain-gut axis",type:"Essay"},
{text:"What is the mechanism of central regulation of appetite? Describe the role of leptin and ghrelin",type:"Essay"},
]},
{year:"Mar 2025",paper:"March 2025 – Basic Neuroscience",questions:[
{text:"Write a short note on the excitation-inhibition balance in the brain and its relevance for schizophrenia",type:"Essay"},
{text:"Polymerase chain reaction",type:"Essay"},
{text:"Write a short note on the dopaminergic pathways in the human brain",type:"Essay"},
{text:"Evoked Response Potentials and its relevance in psychiatric disorders",type:"Essay"},
{text:"Write a short note on the anterior cingulate cortex functions and their relationship to obsessive-compulsive disorder",type:"Essay"},
{text:"What is GWAS? Discuss its relevance in psychiatric disorders",type:"Essay"},
{text:"Write a short note on mirror neurons and their relevance to psychiatry",type:"Essay"},
{text:"Discuss the neuroimmunological theory of Depression",type:"Essay"},
{text:"Write a short note on thalamic nuclei in the human brain",type:"Essay"},
{text:"Write a short note on the types of glutamate receptors",type:"Essay"},
]},
{year:"Sep 2024",paper:"September 2024 – Neurobiology",questions:[
{text:"Discuss the role of gene-environment interactions in the etiology of psychiatric disorders and critically examine its role in transgenerational transmission. Additionally, discuss how DNA methylation, histone modification, and non-coding RNAs contribute to the development and progression of MDD",type:"Essay"},
{text:"Examine the roles of key neurotransmitters like GABA, serotonin, norepinephrine, and acetylcholine in promoting sleep and wakefulness. Additionally, discuss the significance of REM sleep in emotional processing and memory consolidation and how disturbances in REM sleep are linked to mood disorders",type:"Essay"},
{text:"Describe the resting membrane potential and its significance in neuronal function",type:"Short Note"},
{text:"Discuss the anatomical structure and function of the basal ganglia in motor control",type:"Short Note"},
{text:"Discuss the gut-brain axis and its implications for psychiatric disorders",type:"Short Note"},
{text:"Define Neuroplasticity and discuss its role in the pathogenesis of Depression",type:"Short Note"},
{text:"Discuss the role of neuroinflammation in the development of psychiatric disorders, with examples",type:"Short Note"},
{text:"Discuss the relevance of network neuroscience in predicting treatment outcomes in Psychiatry",type:"Short Note"},
]},
{year:"Jun 2024",paper:"June 2024 – Basic Neurosciences",questions:[
{text:"Neuroanatomy of subcortical structures and their relevance in psychiatry",type:"Essay"},
{text:"Neural substrates in memory",type:"Essay"},
{text:"Endocannabinoid receptors in psychiatric disorders",type:"Short Note"},
{text:"Animal models in psychiatric disorders",type:"Short Note"},
{text:"GWAS in psychiatry",type:"Short Note"},
{text:"Role of dopamine in working memory",type:"Short Note"},
{text:"Gate control theory of pain",type:"Short Note"},
{text:"Neuroendocrine hypothesis of depression",type:"Short Note"},
]},
{year:"Dec 2023",paper:"December 2023",questions:[
{text:"Describe the dopaminergic pathways with a note on its clinical relevance in psychiatry",type:"Essay"},
{text:"Neurobiology of sleep and sleep regulation",type:"Essay"},
{text:"Neurotransmitters Serotonin and Norepinephrine",type:"Short Note"},
{text:"Neurobiology of emotions",type:"Short Note"},
{text:"Mirror neurons",type:"Short Note"},
{text:"Gene-environment interactions and epigenetics",type:"Short Note"},
{text:"Neurobiology of stress",type:"Short Note"},
{text:"Pineal gland",type:"Short Note"},
]},
{year:"Dec 2023 (S2)",paper:"December 2023 – Session 2",questions:[
{text:"Role of NMDA receptors in learning and Long-term potentiation",type:"Essay"},
{text:"Describe the functional lobes of the brain along with tests to assess each lobe function",type:"Essay"},
{text:"Reward circuit and its role in addiction",type:"Short Note"},
{text:"Neural basis of Pain",type:"Short Note"},
{text:"Amygdala and its functions",type:"Short Note"},
{text:"EEG in Psychiatry",type:"Short Note"},
{text:"Neuromodulation in psychiatry",type:"Short Note"},
{text:"Neurological soft signs in psychiatry",type:"Short Note"},
]},
{year:"Jul 2023 (S1)",paper:"July 2023 – Session 1",questions:[
{text:"Neurobiology of emotions",type:"Essay"},
{text:"Principles of Synaptic neurotransmission and synaptic plasticity",type:"Essay"},
{text:"Gene-environment interactions and epigenetics",type:"Short Note"},
{text:"Neuro-physiology of Sleep",type:"Short Note"},
{text:"Write a note on Anti-craving agents",type:"Short Note"},
{text:"Describe Fronto-Striatal circuits and its relevance in Psychiatry",type:"Short Note"},
{text:"Enumerate Frontal lobe functions and its assessment",type:"Short Note"},
{text:"Describe the CSF pathway with relevant diagram",type:"Short Note"},
]},
{year:"Jul 2023 (S2)",paper:"July 2023 – Session 2",questions:[
{text:"GABA & Glutamate: Newer Insights on neurotransmission",type:"Essay"},
{text:"Psychoneuroimmunology – relevance to psychiatric disorders",type:"Essay"},
{text:"Reward circuit and its role in addiction",type:"Short Note"},
{text:"Neural basis of pain",type:"Short Note"},
{text:"Neurophysiology of Sleep",type:"Short Note"},
{text:"Note on Mood Stabilizers",type:"Short Note"},
{text:"Role of NMDA receptors in learning",type:"Short Note"},
{text:"Role of cerebellum in cognitive and emotional functions",type:"Short Note"},
]},
{year:"Dec 2022 (S1)",paper:"December 2022 – Session 1",questions:[
{text:"Describe the reward pathway. Explain how different drugs of abuse influence the functioning of the reward pathway",type:"Essay"},
{text:"Describe the neural mechanism of pain perception and its regulation",type:"Essay"},
{text:"Effect of stress on memory",type:"Short Note"},
{text:"Fear conditioning in the amygdala through the process of associative learning",type:"Short Note"},
{text:"Salience network and psychiatric disorders",type:"Short Note"},
{text:"Psychiatric manifestations of endocrine disorders",type:"Short Note"},
{text:"Gut Microbiome and its relevance in Psychiatry",type:"Short Note"},
{text:"Cognitive dysmetria",type:"Short Note"},
]},
{year:"Dec 2022 (S2)",paper:"December 2022 – Session 2",questions:[
{text:"Serotonin-dopamine interactions and their relevance for pathophysiology and treatment of neuropsychiatric disorders",type:"Essay"},
{text:"Biological basis of various pharmacological strategies for control of pain",type:"Essay"},
{text:"Synaptic potentiation and memory",type:"Short Note"},
{text:"Neurophysiological basis of NREM sleep",type:"Short Note"},
{text:"Neuroimmunology of depression",type:"Short Note"},
{text:"Mirror Neurons and their role in social cognition",type:"Short Note"},
{text:"Neuroglia and their role in pathophysiology of psychiatric disorders",type:"Short Note"},
{text:"Epigenetics of schizophrenia spectrum disorders",type:"Short Note"},
]},
{year:"Jun 2022 (S1)",paper:"June 2022 – Session 1",questions:[
{text:"Neural substrates of memory",type:"Essay"},
{text:"Functional neuroanatomy of the subcortical structures and its relevance in Psychiatry",type:"Essay"},
{text:"Animal models of psychiatric disorders",type:"Short Note"},
{text:"Neuroendocrine hypothesis of depression",type:"Short Note"},
{text:"Genome-wide association studies in Psychiatry",type:"Short Note"},
{text:"Endocannabinoid receptors in the human brain",type:"Short Note"},
{text:"Role of dopamine in working memory",type:"Short Note"},
{text:"Gate control theory of pain",type:"Short Note"},
]},
{year:"Jun 2022 (S2)",paper:"June 2022 – Session 2",questions:[
{text:"Serotonin-dopamine interactions and their relevance for pathophysiology and treatment of neuropsychiatric disorders",type:"Essay"},
{text:"Biological basis of various pharmacological strategies for control of pain",type:"Essay"},
{text:"Neurophysiological basis of NREM sleep",type:"Short Note"},
{text:"Mirror Neurons and their role in social cognition",type:"Short Note"},
{text:"Neuroglia and their role in pathophysiology of psychiatric disorders",type:"Short Note"},
{text:"Neuroimmunology of depression",type:"Short Note"},
{text:"Epigenetics of schizophrenia spectrum disorders",type:"Short Note"},
]},
{year:"Nov 2021 (S1)",paper:"November 2021 – Session 1",questions:[
{text:"Briefly describe the neural circuitry of addiction stages and the neurotransmitters involved",type:"Essay"},
{text:"Cellular mechanisms of memory",type:"Essay"},
{text:"Normal human sleep stages",type:"Short Note"},
{text:"Neural pathways underlying anxiety",type:"Short Note"},
{text:"Prenatal stress and psychiatric disorders",type:"Short Note"},
{text:"Cognitive dysmetria and schizophrenia",type:"Short Note"},
{text:"Neural basis of comorbidity of chronic pain and depression",type:"Short Note"},
{text:"Neurobiology of aberrant salience and its relevance in understanding delusions",type:"Short Note"},
]},
{year:"Nov 2021 (S2)",paper:"November 2021 – Session 2",questions:[
{text:"Glutamate and its relevance for neuropsychiatric disorders",type:"Essay"},
{text:"Functional circuitry of the thalamus",type:"Essay"},
{text:"Dopamine receptors in the human brain",type:"Short Note"},
{text:"How does 5-HT2 receptor modulation influence the efficacy and adverse effects of antipsychotic agents?",type:"Short Note"},
{text:"Short term synaptic plasticity",type:"Short Note"},
{text:"Neuroendocrine hypotheses underlying depression",type:"Short Note"},
{text:"Functional neuroanatomy of cerebellum",type:"Short Note"},
{text:"Neurobiology of aberrant salience and its relevance in understanding delusions",type:"Short Note"},
]},
{year:"Jun 2021 (S1)",paper:"June 2021 – Session 1",questions:[
{text:"Describe the reward pathway. Explain how different drugs of abuse influence the functioning of the reward pathway",type:"Essay"},
{text:"Describe the neural mechanism of pain perception and regulation in the brain",type:"Essay"},
{text:"Effect of stress on memory",type:"Short Note"},
{text:"Fear conditioning in the amygdala through the process of associative learning",type:"Short Note"},
{text:"Role of D1 and D2 family of receptors in addiction",type:"Short Note"},
{text:"Gut Microbiome and its relevance in Psychiatry",type:"Short Note"},
{text:"Cognitive dysmetria",type:"Short Note"},
{text:"Psychiatric manifestations of endocrine disorders",type:"Short Note"},
{text:"Salience network and psychiatric disorders",type:"Short Note"},
]},
{year:"Jun 2021 (S2)",paper:"June 2021 – Session 2",questions:[
{text:"Cellular mechanisms of memory",type:"Essay"},
{text:"Describe the various cortico-striato-thalamo-cortical circuits and their functional significance",type:"Essay"},
{text:"Role of D1 and D2 family of receptors in addiction",type:"Short Note"},
{text:"Serotonin transporter (5-HTT) gene polymorphism and psychiatric disorders",type:"Short Note"},
{text:"Cerebellar cognitive affective syndrome",type:"Short Note"},
{text:"Anti-neuronal antibodies and acute psychiatric presentations",type:"Short Note"},
{text:"Prenatal stress and psychiatric disorders",type:"Short Note"},
]},
{year:"Nov 2020 (S1)",paper:"November 2020 – Session 1",questions:[
{text:"Describe the dopaminergic system in human brain and briefly discuss how it is altered in schizophrenia",type:"Essay"},
{text:"Describe the neural mechanisms of memory and briefly explain how these are involved in clinical conditions affecting memory",type:"Essay"},
{text:"Synthesis and metabolism of dopamine in the central nervous system",type:"Short Note"},
{text:"Role of different neurotransmitters in the physiology of sleep",type:"Short Note"},
{text:"Interaction between stress and endocrine system in psychiatric conditions",type:"Short Note"},
{text:"Role of epigenetics in psychiatry",type:"Short Note"},
{text:"Central modulation of pain",type:"Short Note"},
{text:"Tests of Attention",type:"Short Note"},
{text:"Neurobiology of abnormal compulsive behavior in humans",type:"Short Note"},
]},
{year:"Nov 2020 (S2)",paper:"November 2020 – Session 2",questions:[
{text:"Describe the physiology of pain and how peripheral and central systems influence it",type:"Essay"},
{text:"Describe the dopaminergic system in human brain and briefly discuss how it is altered in schizophrenia",type:"Essay"},
{text:"Synthesis and metabolism of dopamine in the central nervous system",type:"Short Note"},
{text:"Synthesis and metabolism of serotonin in the central nervous system",type:"Short Note"},
{text:"NMDA receptor and its role in memory",type:"Short Note"},
{text:"Stages of sleep",type:"Short Note"},
{text:"Papez Circuit",type:"Short Note"},
{text:"Role of epigenetics in psychiatry",type:"Short Note"},
{text:"Role of cerebellum in cognitive and emotional functions",type:"Short Note"},
]},
{year:"Jun 2020 (S1)",paper:"June 2020 – Session 1",questions:[
{text:"Describe the serotonergic system in human central nervous system and its relevance to depression, OCD, and schizophrenia",type:"Essay"},
{text:"Describe the dopaminergic system in human central nervous system and its relevance to schizophrenia",type:"Essay"},
{text:"Synthesis, release, and synaptic clearance of dopamine in human brain",type:"Short Note"},
{text:"Classification of long-term memory in humans",type:"Short Note"},
{text:"Synaptic plasticity",type:"Short Note"},
{text:"Role of epigenetics in psychiatric disorders",type:"Short Note"},
{text:"Relationship between stress and hypothalamo-pituitary-adrenal axis",type:"Short Note"},
]},
{year:"Jun 2020 (S2)",paper:"June 2020 – Session 2",questions:[
{text:"Describe the neurobiology of reward system in humans and its relevance to addictive disorders",type:"Essay"},
{text:"Role of amygdala and orbital-medial prefrontal cortex in the physiology of human emotions",type:"Short Note"},
{text:"Synaptic plasticity",type:"Short Note"},
{text:"Neural basis of pain",type:"Short Note"},
{text:"Cerebellum and psychiatric conditions",type:"Short Note"},
{text:"Neuropathology of Alzheimer's disease",type:"Short Note"},
{text:"Neurobiology of compulsive behavior in humans",type:"Short Note"},
]},
{year:"Nov 2019 (S1)",paper:"November 2019 – Session 1",questions:[
{text:"Describe limbic system and its role in psychiatric disorders",type:"Essay"},
{text:"Serotonin system dysfunction in OCD",type:"Short Note"},
{text:"Neural basis of fear and anxiety",type:"Short Note"},
{text:"Major neuronal signalling pathways",type:"Short Note"},
{text:"Applications of fMRI in psychiatry research",type:"Short Note"},
{text:"Concept of endophenotypes and its application in psychiatric research",type:"Short Note"},
{text:"Neuropathology in Alzheimer's dementia",type:"Short Note"},
]},
{year:"Nov 2019 (S2)",paper:"November 2019 – Session 2",questions:[
{text:"Describe briefly the anatomy of basal ganglia and discuss their involvement in the pathophysiology of psychiatric disorders",type:"Essay"},
{text:"Biology of memory",type:"Short Note"},
{text:"Neural basis of fear and anxiety",type:"Short Note"},
{text:"Genome-wide association studies in psychiatry",type:"Short Note"},
{text:"Neuropathology of schizophrenia",type:"Short Note"},
{text:"Theory of mind",type:"Short Note"},
{text:"Animal models of depression",type:"Short Note"},
]},
{year:"Jun 2019 (S1)",paper:"June 2019 – Session 1",questions:[
{text:"Write an essay on psychoneuroendocrinological basis of psychiatric disorders with specific emphasis on depression",type:"Essay"},
{text:"Write an essay on gene X environment interaction in the causation of psychiatric disorders with specific emphasis on schizophrenia",type:"Essay"},
{text:"Immunological basis of psychiatric disorders",type:"Short Note"},
{text:"Heart rate variability in psychiatric disorders",type:"Short Note"},
{text:"Amyloid plaques",type:"Short Note"},
{text:"Role of cerebellum in psychiatric disorders",type:"Short Note"},
{text:"Functional brain circuits",type:"Short Note"},
]},
{year:"Jun 2019 (S2)",paper:"June 2019 – Session 2",questions:[
{text:"Write an essay on pathophysiology and pathology of dementias",type:"Essay"},
{text:"Serotonergic system in psychiatric disorders",type:"Short Note"},
{text:"Neural basis of reward system and its relevance to addiction",type:"Short Note"},
{text:"Synaptic plasticity and psychiatric disorders",type:"Short Note"},
{text:"Role of GABA in different psychiatric conditions",type:"Short Note"},
{text:"Role of sleep in psychiatric disorders",type:"Short Note"},
{text:"Relevance of fronto-striatal circuit in obsessive-compulsive disorder",type:"Short Note"},
{text:"Genome-Wide Association Study (GWAS) and psychiatric disorders",type:"Short Note"},
]},
{year:"Nov 2018 (S1)",paper:"November 2018 – Session 1",questions:[
{text:"Dopaminergic system and its involvement in schizophrenia",type:"Essay"},
{text:"Neural basis of fear",type:"Short Note"},
{text:"Neurotransmitters in OCD",type:"Short Note"},
{text:"Family studies in bipolar disorder",type:"Short Note"},
{text:"Neuropathology of Alzheimer's disease",type:"Short Note"},
{text:"Application of fMRI in psychiatric research",type:"Short Note"},
{text:"Concept of endophenotypes and its application in psychiatric research",type:"Short Note"},
{text:"Animal models of depression",type:"Short Note"},
]},
{year:"Nov 2018 (S2)",paper:"November 2018 – Session 2",questions:[
{text:"Describe limbic system and its role in psychiatric disorders",type:"Essay"},
{text:"Neural basis of addiction",type:"Short Note"},
{text:"Major neuronal signalling pathways",type:"Short Note"},
{text:"Family studies in schizophrenia",type:"Short Note"},
{text:"Role of immune system in depression and anxiety disorders",type:"Short Note"},
{text:"Concept of endophenotypes and its application in psychiatric research",type:"Short Note"},
{text:"Animal models of OCD",type:"Short Note"},
{text:"Theory of mind",type:"Short Note"},
]},
{year:"Jun 2018 (S1)",paper:"June 2018 – Session 1",questions:[
{text:"Write an essay on serotonergic system in the central nervous system and its role in different psychiatric conditions",type:"Essay"},
{text:"Write an essay on neural basis of memory with clinical implications",type:"Essay"},
{text:"Hypothalamic-pituitary-adrenal axis and psychiatry",type:"Short Note"},
{text:"Epigenetics in psychiatric disorders",type:"Short Note"},
{text:"Amyloid plaques",type:"Short Note"},
{text:"Stages of sleep and their clinical relevance",type:"Short Note"},
{text:"Mono-amine hypothesis of depression",type:"Short Note"},
{text:"Heart rate variability in psychiatric disorders",type:"Short Note"},
]},
{year:"Jun 2018 (S2)",paper:"June 2018 – Session 2",questions:[
{text:"Write an essay on dopaminergic system in the central nervous system and its role in schizophrenia",type:"Essay"},
{text:"Write an essay on social brain in humans and its clinical importance",type:"Essay"},
{text:"Neurobiology of emotions",type:"Short Note"},
{text:"Neurofibrillary tangles",type:"Short Note"},
{text:"Gene X environment interaction in psychiatric disorders",type:"Short Note"},
{text:"Neurobiology of addiction",type:"Short Note"},
{text:"Stages of sleep and their clinical relevance",type:"Short Note"},
{text:"Role of immune system in depression and anxiety disorders",type:"Short Note"},
]},
],
psych:[
{year:"Sep 2025",paper:"Paper 2: Psychology-Sociology-Anthropology",questions:[
{text:"Write a note on the instruments for brief screening of cognitive function and common indications for a detailed neuropsychological assessment",type:"Essay"},
{text:"Write a brief note on the theories of intelligence",type:"Essay"},
{text:"Discuss the projective tests for personality assessment",type:"Essay"},
{text:"List Erikson's psychosocial stages of development and discuss them",type:"Essay"},
{text:"Discuss the principles and clinical applications of CBT in depression",type:"Essay"},
{text:"Write a short note on Dialectical Behaviour Therapy",type:"Short Note"},
{text:"Discuss the application of Existential Theories in Psychotherapy",type:"Essay"},
{text:"Define memory and describe the types of memory",type:"Essay"},
{text:"Write a short note on the social determinants of mental health",type:"Essay"},
{text:"Discuss the cultural aspects of mental health",type:"Essay"},
]},
{year:"Mar 2025",paper:"March 2025 – Psychology, Sociology & Anthropology",questions:[
{text:"Methods of assessment of Personality. Provide example for each method",type:"Essay"},
{text:"Neuropsychological assessment of an older adult with cognitive complaint",type:"Essay"},
{text:"Piaget's stages of intellectual development",type:"Essay"},
{text:"Theories of Motivation",type:"Essay"},
{text:"Assessment of Intelligence Quotient. Name few intelligence tests",type:"Essay"},
{text:"Cognitive models of panic disorder",type:"Essay"},
{text:"Stress diathesis model of depression",type:"Essay"},
{text:"Brief Psychodynamic Psychotherapy",type:"Essay"},
{text:"Ancient Indian Concepts of Psychotherapy",type:"Essay"},
{text:"Psychosocial theories of addictive disorders",type:"Essay"},
]},
{year:"Sep 2024",paper:"September 2024 – Psychology, Sociology & Anthropology",questions:[
{text:"Critically evaluate psychodynamic theories and their application in therapy. Additionally, discuss the relevance of psychodynamic concepts in understanding personality disorders",type:"Essay"},
{text:"Discuss on the classical and operant conditioning principles in detail. Additionally, discuss the application of learning theories in clinical practice",type:"Essay"},
{text:"Outline the key stages of cognitive development according to Jean Piaget",type:"Short Note"},
{text:"Explain the basic concepts of motivation and emotion in psychological theory",type:"Short Note"},
{text:"Detail the relevance of ancient Indian concepts in contemporary psychotherapy",type:"Short Note"},
{text:"Expand on the intersection of gender and mental health from a sociological perspective",type:"Short Note"},
{text:"How did Brown and Harris' study (1978) contribute to developing the vulnerability-stress model in Psychiatry?",type:"Short Note"},
{text:"Describe the neuropsychological assessments of the Pre-Frontal Lobe function",type:"Short Note"},
]},
{year:"Jun 2024",paper:"June 2024 – Psychology, Sociology & Anthropology",questions:[
{text:"What is emotion? Discuss the theories of emotion",type:"Essay"},
{text:"Theoretical concepts of operant conditioning and two applications in behavioural therapy",type:"Essay"},
{text:"Ancient Indian concepts in positive mental health",type:"Short Note"},
{text:"Psychosocial models of OCD",type:"Short Note"},
{text:"Models of Working memory and its application in daily life",type:"Short Note"},
{text:"Tests of intelligence used in India",type:"Short Note"},
{text:"NATs, DAS, Core beliefs in CBT model with examples",type:"Short Note"},
{text:"Trait theories in personality and its clinical relevance",type:"Short Note"},
]},
{year:"Dec 2023 (S1)",paper:"December 2023 – Session 1",questions:[
{text:"Define psychotherapy and discuss three major types of psychotherapy",type:"Essay"},
{text:"Discuss cognitive functions and assessments of occipital and parietal lobe",type:"Essay"},
{text:"Explain Erik Erikson's stages of development and their implications for mental health",type:"Short Note"},
{text:"Discuss various techniques used in psychodynamic therapy",type:"Short Note"},
{text:"Discuss any two behaviour therapy techniques and their learning principles",type:"Short Note"},
{text:"Explain psychosocial theories of addiction",type:"Short Note"},
{text:"Discuss any two theories of intelligence and their implications in intelligence assessment",type:"Short Note"},
{text:"Discuss the components you must cover while psychoeducating the parents of a child with mental retardation",type:"Short Note"},
]},
{year:"Dec 2023 (S2)",paper:"December 2023 – Session 2",questions:[
{text:"Explain principles and indications of neuropsychological assessments and outline executive function tests",type:"Essay"},
{text:"Explain cognitive and psychological model of affective disorders",type:"Essay"},
{text:"Discuss the application of existential and humanistic theories in psychotherapy",type:"Short Note"},
{text:"Discuss principles and applications of CBT",type:"Short Note"},
{text:"Discuss memory dysfunctions and cognitive retraining techniques for the same",type:"Short Note"},
{text:"What are the principles of mindfulness-based interventions, and compare their efficacy to other forms of psychotherapy?",type:"Short Note"},
{text:"Discuss indications of projective assessment and self-rated personality assessment in clinical practice",type:"Short Note"},
{text:"Discuss clinical application of motivation theories",type:"Short Note"},
]},
{year:"Jul 2023 (S1)",paper:"July 2023 – Session 1",questions:[
{text:"Cognitive Behaviour Therapy; Concepts, Principles and Applications",type:"Essay"},
{text:"Write a note on Theories of Personality. Critique on multidimensional approach to personality classification. Briefly write a note on personality assessment",type:"Essay"},
{text:"Write a note on – Intelligence; concept, theories & assessments",type:"Short Note"},
{text:"Discuss about projective assessment and its use in psychological intervention",type:"Short Note"},
{text:"Discuss about temporal lobe deficits and cognitive assessment in temporal lobe",type:"Short Note"},
{text:"Discuss the application of learning principles in psychological interventions",type:"Short Note"},
{text:"Discuss various techniques used in psychodynamic therapy",type:"Short Note"},
{text:"Application of Ancient Indian concepts in Psychotherapy",type:"Short Note"},
]},
{year:"Dec 2022 (S1)",paper:"December 2022 – Session 1",questions:[
{text:"Discuss Beck's longitudinal formulation and its application in clinical practice",type:"Essay"},
{text:"Enumerate the types of personality assessment. Discuss in detail one test each belonging to different categories",type:"Essay"},
{text:"Neuropsychological tests used in assessment of frontal lobe functions",type:"Short Note"},
{text:"Discuss operant conditioning and any two of its clinical applications",type:"Short Note"},
{text:"Types of resistance in psychotherapy",type:"Short Note"},
{text:"Therapeutic techniques from Atharva veda",type:"Short Note"},
{text:"Theories of motivation",type:"Short Note"},
{text:"Metacognition and psychotic symptoms",type:"Short Note"},
]},
{year:"Dec 2022 (S2)",paper:"December 2022 – Session 2",questions:[
{text:"Enumerate the various humanistic and existential theories and discuss their clinical applications",type:"Essay"},
{text:"Discuss the various theories proposed to understand the psychological underpinnings of psychotic symptoms",type:"Essay"},
{text:"Briefly describe steps in cognitive restructuring",type:"Short Note"},
{text:"Briefly outline social learning theories and their clinical applications",type:"Short Note"},
{text:"Transference and countertransference in psychodynamic psychotherapy",type:"Short Note"},
{text:"Briefly outline the important theories of intelligence",type:"Short Note"},
{text:"Outline the neuropsychological tests used in assessment of parietal lobe dysfunctions",type:"Short Note"},
{text:"Psychosocial interventions for addictive disorders",type:"Short Note"},
]},
{year:"Jun 2022 (S1)",paper:"June 2022 – Session 1",questions:[
{text:"Explain the theoretical concept of operant conditioning. Enumerate any two behavioural techniques based on operant conditioning",type:"Essay"},
{text:"Distinguish between core beliefs, negative automatic thoughts and assumptions with suitable examples",type:"Short Note"},
{text:"Briefly outline the tests of intelligence commonly used in India",type:"Short Note"},
{text:"Outline the trait theories of personality and its relevance in present day clinical practice",type:"Short Note"},
{text:"Outline the various psychosocial theories of OCD",type:"Short Note"},
{text:"Briefly describe ancient Indian concepts of positive mental health",type:"Short Note"},
{text:"Discuss the models of working memory and its role in everyday life",type:"Short Note"},
]},
{year:"Jun 2022 (S2)",paper:"June 2022 – Session 2",questions:[
{text:"Define psychotherapy. Enumerate brief psychotherapies and provide details of two brief psychotherapeutic approaches",type:"Essay"},
{text:"Briefly describe Erik Erikson's stages of psychosocial development. How do mastery of these stages or conflicts during these stages potentially manifest in adulthood?",type:"Essay"},
{text:"Briefly describe steps in cognitive restructuring",type:"Short Note"},
{text:"Briefly outline social learning theories and their clinical applications",type:"Short Note"},
{text:"Briefly outline the important theories of intelligence",type:"Short Note"},
{text:"Explain the relevance of ancient Indian concepts of personality in contemporary clinical practice",type:"Short Note"},
{text:"Outline the neuropsychological tests used in assessment of parietal lobe dysfunction",type:"Short Note"},
{text:"Critically analyse Maslow's theory of motivation and its relevance in contemporary society",type:"Short Note"},
]},
{year:"Nov 2021 (S1)",paper:"November 2021 – Session 1",questions:[
{text:"Discuss the principles, rationale and indications of the use of neuropsychological assessments",type:"Essay"},
{text:"Explain the various psychosocial models of depression",type:"Essay"},
{text:"Application of existential therapy in clinical practice",type:"Short Note"},
{text:"Differentiate between any 3 mature and immature defense mechanisms with suitable examples",type:"Short Note"},
{text:"Ancient Indian concept of personality and its present day relevance",type:"Short Note"},
{text:"Discuss any two behaviour therapy techniques based on operant conditioning",type:"Short Note"},
{text:"Briefly enumerate the various types of memory and its dysfunctions",type:"Short Note"},
{text:"Outline the various types of brief psychotherapy",type:"Short Note"},
]},
{year:"Nov 2021 (S2)",paper:"November 2021 – Session 2",questions:[
{text:"Define Intelligence. Discuss in detail any three theories of intelligence",type:"Essay"},
{text:"Explain the theoretical concept of classical conditioning. Briefly describe any two behavioural techniques based on classical conditioning",type:"Essay"},
{text:"Discuss the indications of using projective and objective personality assessments with suitable examples",type:"Short Note"},
{text:"Outline the neuropsychological tests used in assessment of frontal lobe dysfunction",type:"Short Note"},
{text:"Outline the Piaget's stages of cognitive development",type:"Short Note"},
{text:"Compare and contrast the psychosexual stages of Freud with the psychosocial stages of Erikson",type:"Short Note"},
{text:"Explain the relevance of ancient Indian concepts of emotions in contemporary clinical practice",type:"Short Note"},
{text:"Psychosocial interventions for addictive disorders",type:"Short Note"},
]},
{year:"Jun 2021 (S1)",paper:"June 2021 – Session 1",questions:[
{text:"What is intelligence? Discuss various theories of intelligence",type:"Essay"},
{text:"Discuss the key principles of classical conditioning theory and their role in therapeutic procedures",type:"Essay"},
{text:"What are cognitive distortions/errors in thinking? Discuss with examples",type:"Short Note"},
{text:"Social learning theory – principles and applications in social skills training",type:"Short Note"},
{text:"Principles of exposure and response prevention and common pitfalls in the practice of ERP",type:"Short Note"},
{text:"Discuss the role of transference and countertransference in therapy",type:"Short Note"},
{text:"Piaget's stages of cognitive development",type:"Short Note"},
{text:"What are the milestones that mark language development from infancy to late childhood?",type:"Short Note"},
{text:"Emotional regulation",type:"Short Note"},
]},
{year:"Jun 2021 (S2)",paper:"June 2021 – Session 2",questions:[
{text:"Discuss cognitive theory of anxiety disorders",type:"Essay"},
{text:"Explain at least 3 stages of Erikson's theory of psychosocial development",type:"Essay"},
{text:"Basic principles of social learning theory and its applications in clinical practice",type:"Short Note"},
{text:"Structure of neuropsychological assessment",type:"Short Note"},
{text:"What is confabulation? How is confabulation evaluated and addressed in clinical practice?",type:"Short Note"},
{text:"Discuss 'nature vs. nurture' argument in understanding intelligence",type:"Short Note"},
{text:"Ego defence mechanisms",type:"Short Note"},
{text:"Discuss the major components of mind as conceptualized by various schools of Indian thought",type:"Short Note"},
]},
{year:"Nov 2020 (S1)",paper:"November 2020 – Session 1",questions:[
{text:"What are the basic tenets of Cognitive Behavior Therapy? Describe and discuss two major applications of CBT in clinical practice in India",type:"Essay"},
{text:"Critically discuss and evaluate Piaget's theory of cognitive development",type:"Essay"},
{text:"Newer tests of intelligence",type:"Short Note"},
{text:"Defence mechanisms",type:"Short Note"},
{text:"Role of meditation in promoting mental health",type:"Short Note"},
{text:"Motivational Interviewing",type:"Short Note"},
]},
{year:"Nov 2020 (S2)",paper:"November 2020 – Session 2",questions:[
{text:"What is behavior therapy? Discuss in detail the techniques commonly used in behavior therapy",type:"Essay"},
{text:"What are the components of neuropsychological assessment? Describe in detail the clinical assessment of memory",type:"Essay"},
{text:"Theories of emotion",type:"Short Note"},
{text:"Psychological theories of psychotic symptoms",type:"Short Note"},
{text:"Dialectical behavior therapy and personality disorders",type:"Short Note"},
{text:"Development of language",type:"Short Note"},
{text:"Structure of personality according to Freud",type:"Short Note"},
{text:"Yoga and its role in mental health",type:"Short Note"},
]},
{year:"Jun 2020 (S1)",paper:"June 2020 – Session 1",questions:[
{text:"What are the psychosocial and cognitive models of affective disorders?",type:"Essay"},
{text:"Critically discuss methods to assess personality",type:"Essay"},
{text:"Operant conditioning procedures",type:"Short Note"},
{text:"Theories of intelligence",type:"Short Note"},
{text:"Theories of Emotion",type:"Short Note"},
{text:"Psychological theories of delusional thinking",type:"Short Note"},
{text:"Memory – types of dysfunction and methods of assessment",type:"Short Note"},
{text:"Ancient Indian thought and its use in psychotherapy",type:"Short Note"},
{text:"Common developmental disorders",type:"Short Note"},
]},
{year:"Jun 2020 (S2)",paper:"June 2020 – Session 2",questions:[
{text:"Discuss the principles of psychodynamic psychotherapy. What is its current status?",type:"Essay"},
{text:"What are the psychosocial theories of Addiction? How are these theories useful in planning psychological interventions?",type:"Essay"},
{text:"Basic principles of CBT in OCD",type:"Short Note"},
{text:"Psychological theories of panic",type:"Short Note"},
{text:"Assessment of frontal lobe functions",type:"Short Note"},
{text:"Theories of intelligence",type:"Short Note"},
{text:"Psychological theories of hallucinations",type:"Short Note"},
{text:"Carl Rogers' humanistic theory of personality",type:"Short Note"},
]},
{year:"Nov 2019 (S1)",paper:"November 2019 – Session 1",questions:[
{text:"Describe theories of learning and their application in psychiatry",type:"Essay"},
{text:"Attachment theory",type:"Short Note"},
{text:"Cognitive behavioral model for social anxiety",type:"Short Note"},
{text:"Social determinants of depression",type:"Short Note"},
{text:"Culture and course of schizophrenia",type:"Short Note"},
{text:"Assessment of memory",type:"Short Note"},
{text:"Neuropsychological impairments in OCD",type:"Short Note"},
]},
{year:"Nov 2019 (S2)",paper:"November 2019 – Session 2",questions:[
{text:"Discuss defence mechanisms. Illustrate the role of defence mechanisms in psychiatric disorders",type:"Essay"},
{text:"Life events and depression",type:"Short Note"},
{text:"Humanistic theories of personality",type:"Short Note"},
{text:"Projective tests",type:"Short Note"},
{text:"Piagetian model of cognitive development",type:"Short Note"},
{text:"Neuropsychological impairments in bipolar disorder",type:"Short Note"},
]},
{year:"Jun 2019 (S1)",paper:"June 2019 – Session 1",questions:[
{text:"Discuss psychological theories of personality disorder and describe dialectical behaviour therapy for borderline personality disorder",type:"Essay"},
{text:"Discuss the psychosocial theories of addictive behavior. Describe motivational interviewing for treatment of addiction",type:"Essay"},
{text:"Describe neuro-cognitive model of schizophrenia. Explain cognitive remediation therapy",type:"Essay"},
{text:"Cognitive behavioural therapy for panic disorder",type:"Short Note"},
{text:"Assessment of abstraction and concept formation",type:"Short Note"},
{text:"Systematic desensitization",type:"Short Note"},
{text:"Clinical application of positive psychology",type:"Short Note"},
{text:"Cognitive development in children",type:"Short Note"},
{text:"Emotional regulation",type:"Short Note"},
]},
{year:"Jun 2019 (S2)",paper:"June 2019 – Session 2",questions:[
{text:"Discuss humanistic and existential theory of human behaviour and describe their application in therapy",type:"Essay"},
{text:"Describe the cognitive-behavioral model of OCD. Explain CBT and its relevance in management of OCD",type:"Essay"},
{text:"Rationale and indications of projective tests in clinical mental health",type:"Short Note"},
{text:"Object-relation theory",type:"Short Note"},
{text:"Information processing in memory",type:"Short Note"},
{text:"Application of yoga and mindfulness in mental health",type:"Short Note"},
{text:"Object Sorting Test",type:"Short Note"},
{text:"Coping and coping skills training",type:"Short Note"},
]},
{year:"Nov 2018 (S1)",paper:"November 2018 – Session 1",questions:[
{text:"Discuss cognitive-behavioral theories of anxiety disorders",type:"Essay"},
{text:"Theories of learning and their application to behavior therapy",type:"Short Note"},
{text:"Attachment theory and its relevance to understanding human behavior",type:"Short Note"},
{text:"Life events and Depression",type:"Short Note"},
{text:"Assessment of personality",type:"Short Note"},
{text:"Expressed emotions and psychiatric disorders",type:"Short Note"},
{text:"Neuropsychological impairments in Schizophrenia",type:"Short Note"},
]},
{year:"Nov 2018 (S2)",paper:"November 2018 – Session 2",questions:[
{text:"Discuss processes and forms of memory. What are the dysfunctions of memory?",type:"Essay"},
{text:"Humanistic theories of personality",type:"Short Note"},
{text:"Defense mechanisms and their role in human behavior",type:"Short Note"},
{text:"Culture and course of Schizophrenia",type:"Short Note"},
{text:"Cognitive behavioral understanding of OCD",type:"Short Note"},
{text:"Role of Yoga and Meditation in mental health care",type:"Short Note"},
]},
{year:"Jun 2018 (S1)",paper:"June 2018 – Session 1",questions:[
{text:"Discuss the cognitive-behavioral model of generalized anxiety disorder. Describe CBT for GAD",type:"Essay"},
{text:"Discuss the psychosocial theories of addictive behavior. Describe motivational interviewing for treatment of addiction",type:"Essay"},
{text:"Thematic Apperception Test",type:"Short Note"},
{text:"Social motives and its types",type:"Short Note"},
{text:"Stages of language development",type:"Short Note"},
{text:"The role of sympathetic and parasympathetic nervous system in emotion",type:"Short Note"},
{text:"The general adaptation syndrome",type:"Short Note"},
]},
{year:"Jun 2018 (S2)",paper:"June 2018 – Session 2",questions:[
{text:"Discuss the cognitive-behavioral model of panic disorder. Describe briefly CBT for panic disorder",type:"Essay"},
{text:"What is a projective test? Describe Rorschach test",type:"Essay"},
{text:"Operant conditioning",type:"Short Note"},
{text:"Latent learning",type:"Short Note"},
{text:"Humanistic psychology",type:"Short Note"},
{text:"Stages of psychosocial developments as described by Erikson",type:"Short Note"},
]},
]};
